"""add_week2_models

Revision ID: 08d118e8b6ba
Revises: 18f0fabf5473
Create Date: 2026-05-18 15:23:16.036367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d118e8b6ba'
down_revision: Union[str, Sequence[str], None] = '18f0fabf5473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iteration_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('candidate_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['prompt_namespaces.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('query_category', sa.String(length=100), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('negative_rate', sa.Float(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['prompt_namespaces.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('interactions', sa.Column('query_category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'query_category')
    op.drop_table('quality_patterns')
    op.drop_table('iteration_jobs')
    # ### end Alembic commands ###
