"""add_week4_failure_memory

Revision ID: 8ad6b22e6357
Revises: 4ba32bc59759
Create Date: 2026-05-18 19:01:43.750272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad6b22e6357'
down_revision: Union[str, Sequence[str], None] = '4ba32bc59759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('failed_pattern', sa.Text(), nullable=False),
    sa.Column('attempted_fix', sa.Text(), nullable=False),
    sa.Column('evaluation_result', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['prompt_namespaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_memories')
    # ### end Alembic commands ###
